---
title: "Methods-K45"
author: "Evan Odell"
date: "03/09/2018"
output: html_document
---


```{r STM-classification-k45, eval=FALSE, include=FALSE}
library(stm)
library(readr)

lab_corpus_fem_stm <- read_rds("lab_corpus_fem_stm.rds")

set.seed(402)
#topic_model_k30 seed = 9957388
topic_model_k45 <- stm(lab_corpus_fem_stm$documents, 
                    vocab = lab_corpus_fem_stm$vocab, 
                    K = 45, prevalence = ~short_list, 
                    seed = 9957388,
                    data = lab_corpus_fem_stm$meta,
                    verbose = TRUE, init.type = "Spectral")

write_rds(topic_model_k45, "topic_model_k45.rds")
```


```{r STM-men-women-match-k45, eval=FALSE, include=FALSE}
library(readr)
library(stm)
library(viridis)
library(dplyr)
library(igraph)
library(ggplot2)
library(quanteda)

topic_model_k45 <- read_rds("topic_model_k45.rds")

lab_corpus_man_stm <- read_rds("lab_corpus_man_stm.rds")

new_man_k45 <- alignCorpus(new=lab_corpus_man_stm, old.vocab=topic_model_k45$vocab)

#new_man_k45 <- asSTMCorpus(new_man_k45)

topic_model_man_k45 <- fitNewDocuments(model = topic_model_k45, 
                                   documents = new_man_k45$documents,
                                   newData = new_man_k45$meta, 
                                   prevalence = ~short_list, verbose = TRUE)
write_rds(topic_model_man_k45, "topic_model_man_k45.rds")
write_rds(new_man_k45, "new_man_k45.rds")
#summary(topic_model_man_k30)
```


```{r corr_creation-k45, eval=FALSE, include=FALSE}
library(readr)
library(stm)
library(viridis)
library(dplyr)
library(igraph)
library(ggplot2)
library(quanteda)
#library(tidystm)
topic_model_k45 <- read_rds("topic_model_k45.rds")

lab_corpus_fem_stm <- read_rds("lab_corpus_fem_stm.rds")

corr_topic_k45 <- topicCorr(topic_model_k45, method = "huge", verbose = FALSE)

prep_k45 <- estimateEffect(1:45 ~ short_list, topic_model_k45, 
                       meta = lab_corpus_fem_stm$meta, uncertainty = "Global")

write_rds(corr_topic_k45, "corr_topic_k45.rds")

write_rds(prep_k45, "prep_k45.rds")
```

```{r stm-analysis-k45, echo=FALSE, message=FALSE, warning=FALSE, fig.height=7, fig.cap="\\label{k45-network}Fruchterman-Reingold plot of k45 Network"}
library(readr)
library(stm)
library(viridis)
library(dplyr)
library(igraph)
library(ggplot2)
library(quanteda)
#library(tidystm)

corr_topic_k45 <- read_rds("corr_topic_k45.rds")

prep_k45 <- read_rds("prep_k45.rds")

lab_corpus_fem_stm <- read_rds("lab_corpus_fem_stm.rds")

topic_model_k45 <- read_rds("topic_model_k45.rds")

prep_df_k45 <- summary(prep_k45)[[3]]

prep_df_k45 <- as.data.frame(do.call(rbind, prep_df_k45))

prep_df_k45$topic <- NA

prep_df_k45$topic <- rep(1:45, each = 2)

prep_df_k45$type <- row.names(prep_df_k45)

prep_df_k45$type <- gsub("\\.[0-9][0-9]", "", prep_df_k45$type)

prep_df_k45$type <- gsub("\\.[0-9]", "", prep_df_k45$type)

prep_df_k45$type <- gsub("\\.$", "", prep_df_k45$type)

prep_df_k45_coeff <- prep_df_k45 %>% filter(type == "short_listTRUE")

vlabels=NULL
layout=NULL

topics <- 1:nrow(corr_topic_k45$posadj)
  
x <- corr_topic_k45$posadj[topics, topics]
  
g <- igraph::graph.adjacency(x, mode="directed", weighted=TRUE, diag=FALSE)
igraph::E(g)$size <- 1
igraph::E(g)$lty <- 2
igraph::E(g)$color <- "black"
igraph::V(g)$label <- topics

plotcord_k45 <- data.frame(layout_with_fr(g))
  
edgelist_k45 <- get.edgelist(g)

#convert to a four column edge data frame with source and destination coordinates
edges_k45 <- data.frame(plotcord_k45[edgelist_k45[,1],], 
                    plotcord_k45[edgelist_k45[,2],])
colnames(edges_k45) <- c("X1","Y1","X2","Y2")

plotcord_k45$topic <- as.numeric(row.names(plotcord_k45))
  
plotcord_k45 <- plotcord_k45 %>% left_join(prep_df_k45_coeff)

lab_corpus_fem_stm$meta$eo_id <- docnames(lab_corpus_fem_stm$documents)

topic_dt_k45 <- make.dt(topic_model_k45, lab_corpus_fem_stm$meta)

topic_dt_k45$assigned_topic <- colnames(topic_dt_k45[,2:46])[max.col(topic_dt_k45[,2:46],ties.method="random")]

topic_dt_k45$assigned_topic <- as.factor(topic_dt_k45$assigned_topic)

## Reordering x$assigned_topic
topic_dt_k45$assigned_topic <- factor(topic_dt_k45$assigned_topic, 
                           levels=c("Topic1", "Topic2", "Topic3",
                                    "Topic4", "Topic5", "Topic6",
                                    "Topic7", "Topic8", "Topic9",
                                    "Topic10", "Topic11", "Topic12",
                                    "Topic13", "Topic14", "Topic15",
                                    "Topic16", "Topic17", "Topic18",
                                    "Topic19", "Topic20", "Topic21",
                                    "Topic22", "Topic23", "Topic24",
                                    "Topic25", "Topic26", "Topic27",
                                    "Topic28", "Topic29", "Topic30",
                                    "Topic31", "Topic32", "Topic33",
                                    "Topic34", "Topic35", "Topic36",
                                    "Topic37", "Topic38", "Topic39",
                                    "Topic40", "Topic41", "Topic42",
                                    "Topic43", "Topic44", "Topic45"))

topic_dt_k45_2 <- topic_dt_k45 %>% group_by(assigned_topic) %>%
  summarise(count = n()) %>%
  mutate(freq = count/sum(count) )

plotcord_k45$assigned_topic <- paste0("Topic", plotcord_k45$topic)

plotcord_k45 <- plotcord_k45 %>% left_join(topic_dt_k45_2)

p_network_k45 <- ggplot() + 
  geom_segment(aes(x=X1, y=Y1, xend = X2, yend = Y2),
               data=edges_k45, size = 0.5, colour="grey") +
  geom_point(data = plotcord_k45, aes(X1, X2, colour = Estimate, size = freq)) + 
  geom_text(aes(X1, X2, label=topic), hjust="center", vjust="top",
            size = 5, data = plotcord_k45) + 
  scale_colour_viridis(breaks = c(max(plotcord_k45$Estimate),
                                  min(plotcord_k45$Estimate)), 
                       labels = c("More AWS", "More non-AWS"),
                       name=NULL, option = "plasma") + 
  scale_size(guide = "none") + 
  theme_void() + 
  theme(legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),  
    axis.title.x = element_blank(), 
    axis.title.y = element_blank())

ggsave("p_network_k45.svg", plot = p_network_k45, path="plots", device = "svg", width = 20, height = 20, units = "cm")

p_network_k45
```


```{r estimate-table-k45, echo=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)

row.names(prep_df_k45) <- NULL
prep_df_k45$type <- gsub("X.Intercept", "Intercept", prep_df_k45$type)
prep_df_k45$type <- gsub("short_listTRUE", "Shortlist", prep_df_k45$type)

prep_df_k45$stars <- case_when(prep_df_k45$`Pr(>|t|)` < 0.001 ~ "***", 
                               prep_df_k45$`Pr(>|t|)` < 0.01 ~ "**",
                               prep_df_k45$`Pr(>|t|)` < 0.05 ~ "*", 
                               TRUE ~ "")

#   topics <- prep_k45$topics
#   nsim <- 500
#   tables <- vector(mode="list", length=length(topics))
#   for(i in seq_along(topics)) {
#     topic = topics[i]
#     sims <- lapply(prep_k45$parameters[[topic]], function(x) stm:::rmvnorm(nsim, x$est, x$vcov))
#     sims <- do.call(rbind,sims)
#     est<- colMeans(sims)
#     se <- sqrt(apply(sims,2, stats::var))
#     tval <- est/se
#     rdf <- nrow(prep_k45$data) - length(est)
#     p <- 2 * stats::pt(abs(tval), rdf, lower.tail = FALSE)
#     
#     coefficients <- cbind(est, se, tval, p)
#     rownames(coefficients) <- attr(prep_k45$parameters[[1]][[1]]$est, "names") 
#     colnames(coefficients) <- c("Estimate", "Std. Error", "t value", "Pr(>|t|)")
#     tables[[i]] <- coefficients
#   }
#   out <- list(call=prep_k45$call, topics=topics, tables=tables)
#   class(out) <- "lm"
#   return(out)
# }

kable(prep_df_k45,  booktabs = TRUE, longtable = TRUE, 
      caption = "Count and Distribution of Topics -- k45",
      col.names = c("Estimate", "Standard Error", "t value",
                    "P", "Topic",
                    "Type", "Stars"),
      align = c("l","r","r","r","r","r")) %>%
    kable_styling(latex_options = c("HOLD_position",  "repeat_header",
                                    "striped"), full_width = TRUE )
```



```{r stm-excl-coh-k45, echo=FALSE, fig.cap="\\label{k45-coherence}Coherence of k45 Topic Models"}

library(ggrepel)

sem_test_k45 <- semanticCoherence(topic_model_k45, lab_corpus_fem_stm$documents)

exc_test_k45 <- exclusivity(topic_model_k45)

sem_exc_k45 <- tibble::tibble(topic = 1:45, sem_test_k45, exc_test_k45)

p_sem_exc_k45 <- ggplot(sem_exc_k45, aes(y=exc_test_k45, x = sem_test_k45)) + 
  geom_point() + 
  geom_label_repel(aes(label = topic)) +
  #coord_cartesian(xlim = c(-200,0), ylim = c(9.4, 10)) + 
  labs(x="Semantic Coherence", y = "Exclusivity")

ggsave("p_sem_exc_k45.svg", plot = p_sem_exc_k45, path="plots", device = "svg", width = 20, height = 20, units = "cm")

p_sem_exc_k45
```

```{r topic-dt-man-creation-k45, include=FALSE}
library(scales)
library(tidyr)

topic_model_man <- read_rds("topic_model_man_k45.rds")
new_man <- read_rds("new_man_k45.rds")

new_man$meta$eo_id <- docnames(new_man$documents)

topic_man_dt_k45 <- make.dt(topic_model_man, new_man$meta)

topic_man_dt_k45$assigned_topic <- colnames(topic_man_dt_k45[,2:46])[max.col(topic_man_dt_k45[,2:46],ties.method="random")]

topic_man_dt_k45$assigned_topic <- as.factor(topic_man_dt_k45$assigned_topic)

## Reordering x$assigned_topic
# topic_man_dt_k45$assigned_topic <- factor(topic_man_dt_k45$assigned_topic)#, 
#                             levels=c("Topic1", "Topic2", "Topic3",
#                                     "Topic4", "Topic5", "Topic6",
#                                     "Topic7", "Topic8", "Topic9",
#                                     "Topic10", "Topic11", "Topic12",
#                                     "Topic13", "Topic14", "Topic15",
#                                     "Topic16", "Topic17", "Topic18",
#                                     "Topic19", "Topic20", "Topic21",
#                                     "Topic22", "Topic23", "Topic24",
#                                     "Topic25", "Topic26", "Topic27",
#                                     "Topic28", "Topic29", "Topic30",
#                                     "Topic31", "Topic32", "Topic33",
#                                     "Topic34", "Topic35", "Topic36",
#                                     "Topic37", "Topic38", "Topic39",
#                                     "Topic40", "Topic41", "Topic42",
#                                     "Topic43", "Topic44", "Topic45")

topic_man_dt_k45_2 <- topic_man_dt_k45 %>% group_by(assigned_topic) %>%
  summarise(man_count = n()) %>%
  mutate(man_freq = man_count/sum(man_count, na.rm = TRUE),
         assigned_topic = gsub("Topic", "Topic ", assigned_topic))

```

```{r topic-dt3-creation-k45, include=FALSE}
topic_dt_k45_3 <- topic_dt_k45 %>%
  group_by(assigned_topic, short_list) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  spread(key = "short_list", value = "count") %>%
  rename("AWS" = "TRUE", "non_AWS" = "FALSE") %>%
  mutate(AWS_freq = AWS/sum(AWS, na.rm = TRUE),
         non_AWS_freq = non_AWS/sum(non_AWS, na.rm = TRUE),
         assigned_topic = gsub("Topic", "Topic ", assigned_topic)) %>%
  select(assigned_topic, AWS, AWS_freq, non_AWS, non_AWS_freq) %>%
  left_join(topic_man_dt_k45_2)


topic_dt_k45_4 <- topic_dt_k45_3 %>% 
    mutate(AWS_freq = paste0(round((AWS_freq*100), 2), "%"),
          non_AWS_freq = paste0(round((non_AWS_freq*100), 2), "%"),
          AWS = formatC(AWS, big.mark = ","),
          non_AWS = formatC(non_AWS, big.mark = ","),
          man_freq = paste0(round((man_freq*100), 2), "%"),
          man_count = formatC(man_count, big.mark = ","))

```

```{r topic-summary-table-k45, echo=FALSE, results = 'asis'}
library(knitr)
library(kableExtra)

kable(topic_dt_k45_4,  booktabs = TRUE, longtable = TRUE, 
      caption = "Count and Distribution of Topics -- k45",
      col.names = c("Topic Number", "AWS Speeches", "Percent of AWS Speeches",
                    "Non-AWS Speeches", "Percent of non-AWS Speeches",
                    "Male MP Speeches", "Percent of Male MP Speeches"),
      align = c("l","r","r","r","r","r","r")) %>%
    kable_styling(latex_options = c("HOLD_position",  "repeat_header",
                                    "striped"), full_width = TRUE )
```


```{r k45-topic-pyramid, echo=FALSE, fig.height=9, fig.cap="\\label{k45-topic-pyramid-pllot}k45 Pyramid Chart"}

topic_dt_k45_5 <- topic_dt_k45_3 %>% 
  select(-man_count, -man_freq, -non_AWS, -AWS) %>%
  gather("aws_status", "perc", -assigned_topic) %>%
   mutate(assigned_topic = factor(assigned_topic,
                                   levels=c("Topic 1", "Topic 2", "Topic 3",
                                    "Topic 4", "Topic 5", "Topic 6",
                                    "Topic 7", "Topic 8", "Topic 9",
                                    "Topic 10", "Topic 11", "Topic 12",
                                    "Topic 13", "Topic 14", "Topic 15",
                                    "Topic 16", "Topic 17", "Topic 18",
                                    "Topic 19", "Topic 20", "Topic 21",
                                    "Topic 22", "Topic 23", "Topic 24",
                                    "Topic 25", "Topic 26", "Topic 27",
                                    "Topic 28", "Topic 29", "Topic 30",
                                    "Topic 31", "Topic 32", "Topic 33",
                                    "Topic 34", "Topic 35", "Topic 36",
                                    "Topic 37", "Topic 38", "Topic 39",
                                    "Topic 40", "Topic 41", "Topic 42",
                                    "Topic 43", "Topic 44", "Topic 45")))#,

topic_dt_k45_5$perc[is.na(topic_dt_k45_5$perc)] <- 0

p_k45_pyramid <- ggplot(data = topic_dt_k45_5, 
                        aes(x = assigned_topic, y = perc, fill = aws_status)) +
  geom_bar(data = filter(topic_dt_k45_5, aws_status == "non_AWS_freq"),
           stat = "identity" ) + 
  geom_bar(data = filter(topic_dt_k45_5, aws_status == "AWS_freq"),
           stat = "identity", aes(y = -perc) ) + 
  geom_bar(data = filter(topic_dt_k45_5, aws_status == "AWS_freq"),
           stat = "identity", aes(color = aws_status),
           alpha = 0, color = "#641A80") + 
    geom_bar(data = filter(topic_dt_k45_5, aws_status == "non_AWS_freq"),
           stat = "identity", aes(color = aws_status, y = -perc),
           alpha = 0, color = "#F76F5C") + 
  scale_y_continuous(breaks = seq(-0.1, 0.1, 0.025), 
                     labels = paste0(
                       as.character(c(seq(10, 0, -2.5), seq(2.5, 10, 2.5))), "%")) + 
  coord_flip(ylim = c(-0.1, 0.1)) + 
  scale_fill_viridis_d(labels = c("AWS", "non-AWS"),
                       begin = 0.3, end = 0.7, option = "magma", name = "") + 
  labs(x = "Topic", y = "Percentage of Speeches") + 
  theme(legend.position = "bottom")

ggsave("p_k45_pyramid.svg", plot = p_k45_pyramid,
       path="plots", device = "svg", width = 20, height = 20, units = "cm")

p_k45_pyramid
```

```{r k45-topic-bar, echo=FALSE, fig.cap="\\label{k45-topic-bar-plot}k45 Bar Chart"}
p_k45_bar <- ggplot(data = topic_dt_k45_5,
                    aes(x = assigned_topic, y = perc, fill = aws_status)) +
  geom_bar(data = topic_dt_k45_5, stat = "identity", position = "dodge") + 
  scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075),
                     labels = scales::percent) + 
  scale_fill_viridis_d(labels = c("AWS", "non-AWS"),
                       begin = 0.3, end = 0.7, option = "magma", name = "") + 
  labs(x = "Topic", y = "Percentage of Speeches") + 
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 90, hjust = 1))

ggsave("p_k45_bar.svg", plot = p_k45_bar,
       path="plots", device = "svg", width = 20, height = 20, units = "cm")

p_k45_bar
```

```{r stm-topic-words-k45, message=FALSE, warning=FALSE, include=FALSE}
library(tidyr)
topic_words <- labelTopics(topic_model_k45, n = 20, frexweight = 0.5)

topic_words_highest <- tibble::as_tibble(topic_words[[1]])

topic_words_highest <- topic_words_highest %>% unite(V1:V10, sep = ", ") %>%
  rename("highest" = "V1:V10")

topic_words_highest$topic <- paste0("Topic ", row.names(topic_words_highest))

topic_words_frex <- tibble::as_tibble(topic_words[[2]])

topic_words_frex <- topic_words_frex %>% unite(V1:V10, sep = ", ") %>%
  rename("FREX" = "V1:V10")

topic_words_frex$topic <- paste0("Topic ", row.names(topic_words_frex))

topic_words2 <- topic_words_highest %>% left_join(topic_words_frex) %>% 
  select(topic, everything())
```


#### Word Occurences

The table below shows the ten most common words in each topic, and the ten words with the highest FREX score, a measure that uses a harmonic mean of word exclusivity and topic coherence  [@airoldi2016].

```{r topic-words-table-k45, echo=FALSE, results = 'asis'}
library(knitr)
library(kableExtra)

kable(topic_words2,  booktabs = TRUE, longtable = TRUE, 
      caption = "Words in topic - k45",
      col.names = c("Topic Number", "Top Ten Words", "Top Ten FREX")) %>%
    kable_styling(latex_options = c("HOLD_position",  "repeat_header",
                                    "striped"), full_width = TRUE ) %>% 
  column_spec(2:3, width = "6cm")

```


### Full topic model summary - k45


```{r topic-model-k45-summary, echo=FALSE, message=FALSE}
summary(topic_model_k45)
```

### Full topic model estimate summary - k45

```{r topic-model-k45-est-summary, echo=FALSE, message=FALSE}
summary(prep_k45)
```

