---
title: "Methods-K45"
author: "Evan Odell"
date: "03/09/2018"
output: html_document
---


<!-- As STM is an unsupervised model, we used several different validation strategies to ensure the topics themselves are both interesting and relevant [@grimmer2013]. @quinn2010 suggest that topics are valid if they correspond to external events. Figure \ref{k45-military-intervention-validity} shows the number of speeches by female Labour MPs on the "Military Intervention" topic, with a spike in 2003 (at the start of the Iraq War), another spike in 2008 and 2009, as the bulk of British troops left Iraq, a small spike in 2011 coinciding with UK participation in NATO's military intervention in Libya, and debate in 2014--2016 over UK participation in military interventions in the Syrian Civil War. Figure \ref{k45-housing-validity} shows the increased importance of housing in UK politics, with the number of speeches rising alongside UK housing prices. -->
<!--
```{r validation-prep, include=FALSE}
library(lubridate)
library(ggplot2)

head(topic_dt_k45)

topic_dt_k45_valid <- topic_dt_k45 %>% 
  group_by(assigned_topic, year) %>%
  summarise(count = n())

test41 <- topic_dt_k45_valid %>% filter(assigned_topic == "Topic41")

plot41 <- ggplot(aes(x=year, y = count), data = test41) +
  geom_point()

test44 <- topic_dt_k45_valid %>% filter(assigned_topic == "Topic44")

plot44 <- ggplot(aes(x=year, y = count), data = test44) +
  geom_point()

plot44

test28 <- topic_dt_k45_valid %>% filter(assigned_topic == "Topic28")

plot28 <- ggplot(aes(x=year, y = count), data = test28) +
  geom_point()

plot28
```


```{r intervention-plot, echo=FALSE,fig.cap="\\label{k45-military-intervention-validity}Number of Speeches in \"Military Intervention\" Topic per Year"}
test35 <- topic_dt_k45_valid %>% filter(assigned_topic == "Topic35")

plot35 <- ggplot(aes(x=year, y = count), data = test35) +
  geom_line()

plot35
```



```{r housing-plot, echo=FALSE,fig.cap="\\label{k45-housing-validity}Number of Speeches in \"Housing\" Topic per Year"}

test5 <- topic_dt_k45_valid %>% filter(assigned_topic == "Topic5")

plot5 <- ggplot(aes(x=year, y = count), data = test5) +
  geom_line()

plot5
```
-->

### Full topic model summary - k45


```{r topic-model-k45-summary, echo=FALSE, message=FALSE}
summary(topic_model_k45)
```

### Full topic model estimate summary - k45

```{r topic-model-k45-est-summary, echo=FALSE, message=FALSE}
summary(prep_k45)
```

