---
title: "Topic Model Coherence Testing"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
library(stm)
library(quanteda)
library(quanteda.corpora)
library(topicmodels)
library(readr)

lab_corpus <- read_rds("lab_corpus.rds")

lab_corpus_fem <- corpus_subset(lab_corpus, gender=="Female")

parliament_stopwords <- c(stopwords(), "hon", "rose", "n", "friend", "way", 
                          "give", "gentleman", "right", "percent", "per",
                          "cent", "prime", "minister", "c")
rm(lab_corpus)
#ndoc(lab_corpus_fem)

lab_corpus_fem_dfm <- dfm(lab_corpus_fem, remove_punct = TRUE,
                           remove = parliament_stopwords, verbose = TRUE) #%>% 
#  dfm_trim(min_termfreq = 0.95, termfreq_type = "quantile", 
#           max_docfreq = 0.1, docfreq_type = "prop")


lab_corpus_fem_stm <- convert(lab_corpus_fem_dfm, to = "stm", docvars = NULL)

lab_corpus_fem_stm$meta$short_list <- as.factor(lab_corpus_fem_stm$meta$short_list)

# topic_model2 <- stm(lab_corpus_fem_stm$documents, 
#                     vocab = lab_corpus_fem_stm$vocab, 
#                     K = 2, content = ~short_list, 
#                     data = lab_corpus_fem_stm$meta,
#                     verbose = TRUE, init.type = "Spectral")

topic_model2 <- stm(lab_corpus_fem_stm$documents, 
                    vocab = lab_corpus_fem_stm$vocab, 
                    K = 0, prevalence = ~short_list, 
                    data = lab_corpus_fem_stm$meta,
                    verbose = TRUE, init.type = "Spectral")

write_rds(topic_model2, "stm-topic-model2.rds")

```

<!--

```{r}
library(textmineR)
library(readr)
library(topicmodels)

lda_10 <- read_rds("topic-models/fem_lda-10-topics.rds")

lda_20 <- read_rds("topic-models/fem_lda-20-topics.rds")

lda_50 <- read_rds("topic-models/fem_lda-50-topics.rds")


```



```{r}
data(movie_review, package = "text2vec")

str(movie_review)
#> 'data.frame':    5000 obs. of  3 variables:
#>  $ id       : chr  "5814_8" "2381_9" "7759_3" "3630_4" ...
#>  $ sentiment: int  1 1 0 0 1 1 0 0 0 1 ...
#>  $ review   : chr  "With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd docu"| __truncated__ "\\\"The Classic War of the Worlds\\\" by Timothy Hines is a very entertaining film that obviously goes to great"| __truncated__ "The film starts with a manager (Nicholas Bell) giving welcome investors (Robert Carradine) to Primal Park . A s"| __truncated__ "It must be assumed that those who praised this film (\\\"the greatest filmed opera ever,\\\" didn't I read some"| __truncated__ ...

# create a document term matrix 
dtm <- CreateDtm(doc_vec = movie_review$review, # character vector of documents
                 doc_names = movie_review$id, # document names
                 ngram_window = c(1, 2), # minimum and maximum n-gram length
                 stopword_vec = c(tm::stopwords("english"), # stopwords from tm
                                  tm::stopwords("SMART")), # this is the default value
                 lower = TRUE, # lowercase - this is the default value
                 remove_punctuation = TRUE, # punctuation - this is the default
                 remove_numbers = TRUE, # numbers - this is the default
                 verbose = FALSE, # Turn off status bar for this demo
                 cpus = 2) # default is all available cpus on the system


# start with a sample of 500 documents so our example doesn't take too long
dtm_sample <- dtm[ sample(1:nrow(dtm), 500) , ]

# Fit a Latent Dirichlet Allocation model
# note the number of topics is arbitrary here
# see extensions for more info
model <- FitLdaModel(dtm = dtm_sample, 
                     k = 100, 
                     iterations = 500,
                     alpha = 0.1, # this is the default value
                     beta = 0.05, # this is the default value
                     cpus = 2) 

model$ll <- CalcLikelihood(dtm = dtm_sample, 
                           phi = model$phi, 
                           theta = model$theta,
                           cpus = 2)

model$r2 <- CalcTopicModelR2(dtm = dtm_sample, 
                             phi = model$phi,
                             theta = model$theta,
                             cpus = 2)

model$coherence <- CalcProbCoherence(phi = model$phi, dtm = dtm_sample, M = 5)
```


-->
