---
title: "Untitled"
author: "Evan Odell"
date: "25/08/2018"
output:
  pdf_document: default
  html_document: default
---




```{r STM-classification, eval=FALSE, include=FALSE}
library(stm)
library(quanteda)
library(quanteda.corpora)
library(topicmodels)
library(readr)
set.seed(402)
#topic_model_k30 seed = 9957388
topic_model_k30 <- stm(lab_corpus_fem_stm$documents, 
                    vocab = lab_corpus_fem_stm$vocab, 
                    K = 30, prevalence = ~short_list, 
                    seed = 9957388,
                    data = lab_corpus_fem_stm$meta,
                    verbose = TRUE, init.type = "Spectral")

write_rds(topic_model_k30, "topic_model_k30.rds")
```


```{r STM-men-women-match, eval=FALSE, include=FALSE}
library(readr)
library(stm)
library(viridis)
library(dplyr)
library(igraph)
library(ggplot2)
library(quanteda)

topic_model_k30 <- read_rds("topic_model_k30.rds")

lab_corpus_man_stm <- read_rds("lab_corpus_man_stm.rds")

new_man_k30_k30 <- alignCorpus(new=lab_corpus_man_stm, old.vocab=topic_model_k30$vocab)

#new_man_k30 <- asSTMCorpus(new_man_k30)

topic_model_man_k30 <- fitNewDocuments(model = topic_model_k30, 
                                   documents = new_man_k30_k30$documents,
                                   newData = new_man_k30$meta, 
                                   prevalence = ~short_list, verbose = TRUE)
write_rds(topic_model_man_k30, "topic_model_man_k30.rds")
write_rds(new_man_k30_k30, "new_man_k30_k30.rds")
summary(topic_model_man_k30)

#x <- topicCorr(topic_model_man_k30)
```

```{r stm-analysis, echo=FALSE, message=FALSE, warning=FALSE, fig.height=7}
library(readr)
library(stm)
library(viridis)
library(dplyr)
library(igraph)
library(ggplot2)
library(quanteda)
#library(tidystm)
topic_model_k30 <- read_rds("topic_model_k30.rds")

lab_corpus_fem_stm <- read_rds("lab_corpus_fem_stm.rds")

corr_topic <- topicCorr(topic_model_k30, method = "huge", verbose = FALSE)

prep <- estimateEffect(1:30 ~ short_list, topic_model_k30, 
                       meta = lab_corpus_fem_stm$meta, uncertainty = "Global")

prep_df <- summary(prep)[[3]]

prep_df <- as.data.frame(do.call(rbind, prep_df))

prep_df$topic <- rep(1:30, each = 2)

prep_df$type <- row.names(prep_df)

prep_df$type <- gsub("\\.[0-9][0-9]", "", prep_df$type)

prep_df$type <- gsub("\\.[0-9]", "", prep_df$type)

prep_df$type <- gsub("\\.$", "", prep_df$type)

prep_df_coeff <- prep_df %>% filter(type == "short_listTRUE")

vlabels=NULL
layout=NULL

topics <- 1:nrow(corr_topic$posadj)
  
x <- corr_topic$posadj[topics, topics]
  
g <- igraph::graph.adjacency(x, mode="directed", weighted=TRUE, diag=FALSE)
igraph::E(g)$size <- 1
igraph::E(g)$lty <- 2
igraph::E(g)$color <- "black"
igraph::V(g)$label <- topics

plotcord <- data.frame(layout_with_fr(g))
  
edgelist <- get.edgelist(g)

#convert to a four column edge data frame with source and destination coordinates
edges <- data.frame(plotcord[edgelist[,1],], plotcord[edgelist[,2],])
colnames(edges) <- c("X1","Y1","X2","Y2")

plotcord$topic <- as.numeric(row.names(plotcord))
  
plotcord <- plotcord %>% left_join(prep_df_coeff)

lab_corpus_fem_stm$meta$eo_id <- docnames(lab_corpus_fem_stm$documents)

topic_dt <- make.dt(topic_model_k30, lab_corpus_fem_stm$meta)

topic_dt$assigned_topic <- colnames(topic_dt[,2:31])[max.col(topic_dt[,2:31],ties.method="random")]

topic_dt$assigned_topic <- as.factor(topic_dt$assigned_topic)

## Reordering x$assigned_topic
topic_dt$assigned_topic <- factor(topic_dt$assigned_topic, 
                           levels=c("Topic1", "Topic2", "Topic3", 
                                    "Topic4", "Topic5", "Topic6",
                                    "Topic7", "Topic8", "Topic9",
                                    "Topic10", "Topic11", "Topic12", 
                                    "Topic13", "Topic14", "Topic15", 
                                    "Topic16", "Topic17", "Topic18", 
                                    "Topic19", "Topic20", "Topic21", 
                                    "Topic22", "Topic23", "Topic24", 
                                    "Topic25", "Topic26", "Topic27", 
                                    "Topic28", "Topic29", "Topic30"))

topic_dt2 <- topic_dt %>% group_by(assigned_topic) %>%
  summarise(count = n()) %>%
  mutate(freq = count/sum(count) )

plotcord$assigned_topic <- paste0("Topic", plotcord$topic)

plotcord <- plotcord %>% left_join(topic_dt2)

p_network_k30 <- ggplot() + 
  geom_segment(aes(x=X1, y=Y1, xend = X2, yend = Y2),
               data=edges, size = 0.5, colour="grey") +
  geom_point(data = plotcord, aes(X1, X2, colour = Estimate, size = freq)) + 
  geom_text(aes(X1, X2, label=topic), hjust="center", vjust="top",
            size = 5, data = plotcord) + 
  scale_colour_viridis(breaks = c(max(plotcord$Estimate),
                                  min(plotcord$Estimate)), 
                       labels = c("More AWS", "More non-AWS"),
                       name=NULL, option = "plasma") + 
  scale_size(guide = "none") + 
  theme_void() + 
  theme(legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),  
    axis.title.x = element_blank(), 
    axis.title.y = element_blank())

p_network_k30
```

```{r topic-dt-man-creation, include=FALSE}
library(scales)
library(tidyr)

topic_model_man_k30 <- read_rds("topic_model_man_k30.rds")
new_man_k30 <- read_rds("new_man_k30.rds")

new_man_k30$meta$eo_id <- docnames(new_man_k30$documents)

topic_man_dt_k30 <- make.dt(topic_model_man_k30, new_man_k30$meta)

topic_man_dt_k30$assigned_topic <- colnames(topic_man_dt_k30[,2:31])[max.col(topic_man_dt_k30[,2:31],ties.method="random")]

topic_man_dt_k30$assigned_topic <- as.factor(topic_man_dt_k30$assigned_topic)

## Reordering x$assigned_topic
topic_man_dt_k30$assigned_topic <- factor(topic_man_dt_k30$assigned_topic, 
                           levels=c("Topic1", "Topic2", "Topic3", 
                                    "Topic4", "Topic5", "Topic6",
                                    "Topic7", "Topic8", "Topic9",
                                    "Topic10", "Topic11", "Topic12", 
                                    "Topic13", "Topic14", "Topic15", 
                                    "Topic16", "Topic17", "Topic18", 
                                    "Topic19", "Topic20", "Topic21", 
                                    "Topic22", "Topic23", "Topic24", 
                                    "Topic25", "Topic26", "Topic27", 
                                    "Topic28", "Topic29", "Topic30"))

topic_man_dt_k302 <- topic_man_dt_k30 %>% group_by(assigned_topic) %>%
  summarise(man_count = n()) %>%
  mutate(man_freq = man_count/sum(man_count, na.rm = TRUE),
         assigned_topic = gsub("Topic", "Topic ", assigned_topic))

```

```{r topic-dt3-creation, include=FALSE}
topic_dt3 <- topic_dt %>% group_by(assigned_topic, short_list) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  spread(key = "short_list", value = "count") %>%
  rename("AWS" = "TRUE", "non_AWS" = "FALSE") %>%
  mutate(AWS_freq = AWS/sum(AWS, na.rm = TRUE),
         non_AWS_freq = non_AWS/sum(non_AWS, na.rm = TRUE),
         assigned_topic = gsub("Topic", "Topic ", assigned_topic)) %>%
  select(assigned_topic, AWS, AWS_freq, non_AWS, non_AWS_freq) %>%
  left_join(topic_man_dt_k302)


topic_dt4 <- topic_dt3 %>% 
    mutate(AWS_freq = paste0(round((AWS_freq*100),2), "%"),
          non_AWS_freq = paste0(round((non_AWS_freq*100),2), "%"),
          AWS = formatC(AWS, big.mark = ","),
          non_AWS = formatC(non_AWS, big.mark = ","),
          man_freq = paste0(round((man_freq*100),2), "%"),
          man_count = formatC(man_count, big.mark = ","))

```


```{r topic-summary-table, echo=FALSE, results = 'asis'}
library(knitr)
library(kableExtra)

kable(topic_dt4, booktabs = TRUE, longtable = TRUE, 
      caption = "Count and Distribution of Topics",
      col.names = c("Topic Number", "AWS Speeches", "Percent of AWS Speeches",
                    "Non-AWS Speeches", "Percent of non-AWS Speeches",
                    "Male MP Speeches", "Percent of Male MP Speeches"),
      align = c("l","r","r","r","r","r","r")) %>%
    kable_styling(latex_options = c("hold_position",  "repeat_header",
                                    "striped"), full_width = TRUE )
```

```{r top-n-topics, eval=FALSE, include=FALSE}

aws_top10 <- top_n(topic_dt3, 10, AWS)
non_aws_top10 <- top_n(topic_dt3, 10, non_AWS)

cor.test(topic_dt3$non_AWS_freq, topic_dt3$man_freq, na.rm = TRUE)

topic_dt5 <- topic_dt3 %>% select(assigned_topic, AWS_freq, non_AWS_freq, man_freq)

df <- table(topic_dt5)

# run test
mantelhaen.test(topic_dt3$assigned_topic)

```


```{r stm-topic-words, message=FALSE, warning=FALSE, include=FALSE, results='asis'}
library(tidyr)
topic_words <- labelTopics(topic_model_k30, n = 10, frexweight = 0.5)

topic_words2 <- tibble::as.tibble(topic_words[[1]])

topic_words2 <- topic_words2 %>% unite(V1:V10, sep = ", ")

topic_words2$topic <- paste0("Topic ", row.names(topic_words2))

topic_words2 <- topic_words2 %>% select(topic, everything())
```

```{r topic-words-table, echo=FALSE, results = 'asis'}
library(knitr)
library(kableExtra)

kable(topic_words2, booktabs = TRUE, longtable = TRUE, 
      col.names = c("Topic Number", "Top Ten Words")) %>%
    kable_styling(latex_options = c("hold_position",  "repeat_header",
                                    "striped"), full_width = TRUE ) %>% 
  column_spec(2, width = "12cm")
```

```{r tidy-text-testing, eval=FALSE, include=FALSE}
library(tidytext)
test3 <- tidytext::tidy(topic_model_k30, matrix = "gamma",
                        document_names = rownames(topic_model_k30))


test4 <- test3  %>%
  group_by(document) %>%
  top_n(1, gamma) %>%
  ungroup() %>%
  arrange(document, -gamma)

test5 <- tidytext::tidy(topic_model_k30, matrix = "beta")

test6 <- test5  %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

head(test6)
```

